language: node_js
node_js:
  - 12
instal:
  - npm install
  - npm run join
script:
  - npm run build
  - npm run publish

branches:
  only:
    - master
    - dev
deploy:
  provider: pages
  verbose: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  on:
    branch: master

